---
charts:
  - name: memcached
    # https://artifacthub.io/packages/helm/bitnami/memcached
    version: 7.4.11
    repository:
      url: https://charts.bitnami.com/bitnami
  - name: node-feature-discovery
    # https://artifacthub.io/packages/helm/node-feature-discovery/node-feature-discovery
    version: 0.15.4
    repository:
      url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  - name: prometheus-pushgateway
    # https://artifacthub.io/packages/helm/prometheus-community/prometheus-pushgateway
    version: 2.14.0
    repository:
      url: https://prometheus-community.github.io/helm-charts
  - name: keycloak
    # https://artifacthub.io/packages/helm/bitnami/keycloak
    version: 21.8.0
    repository:
      url: https://charts.bitnami.com/bitnami
  - name: pxc-operator
    # https://artifacthub.io/packages/helm/percona/pxc-operator
    version: 1.14.2
    repository:
      url: https://percona.github.io/percona-helm-charts
  - name: cloudnative-pg
    # https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
    version: 0.21.5
    repository:
      url: https://cloudnative-pg.github.io/charts
  - name: rook-ceph
    # https://artifacthub.io/packages/helm/rook/rook-ceph
    version: 1.14.8
    repository:
      url: https://charts.rook.io/release
  - name: rook-ceph-cluster
    # https://artifacthub.io/packages/helm/rook/rook-ceph-cluster
    version: 1.14.5
    repository:
      url: https://charts.rook.io/release
  - name: mariadb-operator
    # https://artifacthub.io/packages/helm/mariadb-operator/mariadb-operator
    version: 0.29.0
    repository:
      url: https://helm.mariadb.com/mariadb-operator
  - name: rabbitmq-cluster-operator
    # https://artifacthub.io/packages/helm/bitnami/rabbitmq-cluster-operator
    version: 4.3.11
    repository:
      url: https://charts.bitnami.com/bitnami
  - name: kube-prometheus-stack
    # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
    version: 61.2.0
    repository:
      url: https://prometheus-community.github.io/helm-charts
  - name: kubernetes-dashboard
    # https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard
    version: 7.5.0
    repository:
      url: https://kubernetes.github.io/dashboard
  - name: headlamp
    # https://artifacthub.io/packages/helm/headlamp/headlamp
    version: 0.23.0
    repository:
      url: https://headlamp-k8s.github.io/headlamp/
# YAOOK charts
  - name: crds
    version: 0.20240704.1
    repository:
      url: https://charts.yaook.cloud/operator/stable
  - name: infra-operator
    version: 0.20240704.1
    repository:
      url: https://charts.yaook.cloud/operator/stable
  - name: keystone-operator
    version: 0.20240704.1
    repository:
      url: https://charts.yaook.cloud/operator/stable
  - name: keystone-resources-operator
    version: 0.20240704.1
    repository:
      url: https://charts.yaook.cloud/operator/stable
