---
charts:
  - name: pxc-operator
    version: 1.14.1
    repository:
      url: https://percona.github.io/percona-helm-charts
  - name: cloudnative-pg
    version: 0.21.5
    repository:
      url: https://cloudnative-pg.github.io/charts
  - name: rook-ceph
    version: 1.14.6
    repository:
      url: https://charts.rook.io/release
  - name: rook-ceph-cluster
    version: 1.14.5
    repository:
      url: https://charts.rook.io/release
  - name: mariadb-operator
    version: 0.29.0
    repository:
      url: https://helm.mariadb.com/mariadb-operator
  - name: rabbitmq-cluster-operator
    version: 4.3.6
    repository:
      url: https://charts.bitnami.com/bitnami
  - name: kube-prometheus-stack
    version: 60.2.0
    repository:
      url: https://prometheus-community.github.io/helm-charts
  - name: kubernetes-dashboard
    version: 7.5.0
    repository:
      url: https://kubernetes.github.io/dashboard
