---
- secret:
    name: SECRET_OSISM_KUBERNETES
    data:
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - iDaw8gx6xIPxwlqD0clSPy/cOe9wS3nDgPfyrNuvYl2Luk7pmduv5Eg49K90yzhYtVHJP
          8jmlIG9qtm8ipWaiYdJhpGjK14wTHXyh4T+nIhmUkQ0AiHt2bO2DQ30gQYt7lI7TKTT7D
          nj9x8JXZqCj8OBD2Tc0hMjYnEACSbD+9fLpKFRPxol9H3r4fiGDUZQk43+T8i9Yqnid49
          zILapry7rubmBb2u2+y7xyTsCGzWiA6N+vriajIXhJ+kXHgrPvWVywrbt3ekiNHnJhqY3
          WUy5RoQ5NHN0HG4wxVw11aVoBrdXSt1r7DbpcSe8hcgqr+EIh5nQJdmGjqLwRrVF8/4Gn
          5PHoRwtwHYoQDIiRNZySqN5TbNSuFV6yMOJ2qfZ3F2kRlClo3LQ03Jl0irNgnpv0Bnxz7
          62olOrIDpBstXcZ6M3PSlce/T2M3xYoLikv0+oEnLmQlSK93JWZTW3hfS3dwU2Lj8JW9F
          95ML4TODom+BFbRPVfyi0twuXUBSbjuJ7ycR0pFpUQq9hp+1Nf1jk49vkWgCyKm6ORqPz
          yin6dX+7yNVff4gb2QLM35BbjA8+hdYK6+Fn85rM3y/0fmieUhVITqrr9YxLAgGMqJmLH
          UQetfLOmsp5WXa5Q5Ca3xRQWqOOJwLkDgWcA4ciufEnOE6THJ2fFvWl++/KfRA=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - ZSMvkxFt3SGVbFYEnDytJrT+t3ueb95QQCkxrWHq4MO1SHPH+kJlfnfXcL1j8eymeKj81
          bZEOEaULeNyBrGLUbX/6wzEawIu0yJgBabwrZY0WfdxAysc+9Ztj5Ym+IdetcBvd/yOz6
          elEN+x7VTB/4iQlOeeZIkDCLS0vD2DyZfYYLNk2OF+7chLd9dmYkKZRLbBBduJc/TadDH
          0TbrU2ZEmTRmo0WT0xwqNFfJQm8HBpp0Lu2NEPn+0TRbtJqEWyHOddMTvjhFBsW2JMJBA
          zGxIK+lyZLecSysDMM2+xwuK7feICInzKb2FBF4ufFwRcxfc5zUoVLguEKZjnUBH8A/2v
          20GDfMD2ZidsZ58ZRNG9tOrARxUhbrmV9t47k4azUy8eGMUdAF7ezQE5v8n2iMFl88z7j
          +3zVAZhBx7DRWtRYEJ/7EffoOvs1KR2FyWHrA8JhD3fI7t10zULMPcvyDen1ee9rJu90S
          6AFgdHeHilmRoZ0Uuy5Nm9jBpZN33YfeLW2Npl1cjSzQc3+/CwwVoJvTSiSf0W8TAYl76
          OD2AyB384c7FXnHCYfmrvA79HaWtWG5qlTCqCsJoKDmNSLX4+DfKRPufmoWJ39/4TMVwG
          3FY3ZMildYo1Bol1VfZrGlAky1zcFNbQmrjUpi3FB74/YyJnYkYKnjcEgA20Zo=

- semaphore:
    name: semaphore-osism-kubernetes-push
    max: 1

- job:
    name: osism-kubernetes-build
    pre-run: zuul-playbooks/pre.yml
    run: zuul-playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: abstract-osism-kubernetes-push
    abstract: true
    semaphores:
      - name: semaphore-osism-kubernetes-push
    pre-run: zuul-playbooks/pre.yml
    run: zuul-playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital
      push_image: true

- job:
    name: osism-kubernetes-push
    parent: abstract-osism-kubernetes-push
    secrets:
      - name: secret
        secret: SECRET_OSISM_KUBERNETES
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - hadolint
        - osism-kubernetes-build
        - yamllint
    gate:
      jobs:
        - ansible-lint
        - hadolint
        - osism-kubernetes-build
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - hadolint
        - yamllint
    periodic-midnight:
      jobs:
        - osism-kubernetes-push
    post:
      jobs:
        - osism-kubernetes-push:
            branches: main
    tag:
      jobs:
        - osism-kubernetes-push
