---
- secret:
    name: SECRET_OSISM_KUBERNETES
    data:
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - GO95CQZOtTtCBFwAgb0GgKKqirKyBwm5wCWf30w3hTSDAZwS846n043XGewSYBeded4s3
          hQXnhAxOB1Zf+yoh0PxtYU7zYVisM/Gv9lNB+gXqup+8IdF+gZbSMu+yFqdvnHTBZHa8C
          yREamwskIbzRWWSXkSz4t/GOwiNesIE55U/ZnrljpOmNeHt0r9xDLnCiNxvZAuyBjdOau
          UJaYNbRI5VTO/Y95nZKalrYjVBrFhGiTGCXBLFEtD0p1JaVVTTEuSY1BxiE4c2/Rm5IsV
          a4PIiLsnfTt413IKzTFwRDFl7E0JjQFphjZ/+qn5mlhcrz2yWtbH8Icr/kLArh2D8kKTv
          EkQLOZRFNdVkC4hgDOWMnSPeOKdnqgW2m3bHF8dVooCVRk/xUSOR1CEbwvjos7Xr0sEWr
          z/g2KI3z19rfLwBqiUAMtB5l0z0UMbmW4St3DclbFXhj5RogpndwvYtoN595/dg/ckq5I
          Kme8hLqBq3MxMZJkzh96Pb8RmvKEdw/OFnF4Kg+B7PTyEi/PzLNdyf6/1BypGRNt1jh3V
          +KVuXh2lFIE+nghS/RrC9Kkl39hSbhH7lfL3773pD4ek8VZ1FsJmB246H9gjAjiXcJoS5
          sUyYlqxZAXadv6A24gotHD0jFgKt+ez4kPlwz0BwnuyKnDWnYyVrQoVbaPQq2w=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - BfO1CPHc4tDsIZQv54XdJITkg5+hDNtIHBgwXMRG4/aGnEFZRLADWI087HHM9Hk7WW+fz
          D5KtR99d29yutuxFTuDRbeUoQbIqZzXS2THn8Cj47jsfqQ2GM/kCYH+6K9yF6GeVuZTnG
          EhGSJezKtwD9rxSMUP6Ahb0nDZTHhFBYoItVtfWU4uodrUy2jNv2rL5FgABXYR3MLWAV4
          ssxP1KTuYBGVBZJMkegK5BGznB8LRCp8uUMXHCTuPwXRAfSDMnH3KoS2eQvy4QiIutyAm
          Z3ctR/PU/0o3uASRpPT+KvvvTaVZU/32PmJH/rfc1W2e3cqF9D3K/yUVLzSb+r3nM6JAS
          F+UoNUfcedRVbETIMK5vrmbbWEGwr28uOYsgJRliY4bBqH4yLJkuuSE1trwX9qSRFXCSJ
          w3vevqOae79+m0Z7hMUH4ltBGI1DxQ/TqGroTrg2A5CiIQQWYRLgF8ZO8p4ub9aiEJCKz
          y9eoVHetQgG6/u4AfbqNHQtiRJSV5g2d7x8UE6Nn5GmBcgdhoZC/faFPkII07bj0jAH37
          mOySq2D+ogWAaQAWkiSJ67VcVXfO2oJ1IRORIGB7h9ZWDhh13CC3axtVdDDj9i7HO93JF
          YP8nvHo9rIsZkM2M359rMNAViSKRfZ6vLLA9W61xkA+8f1EYXhqMQl/AJTeFbY=

- semaphore:
    name: semaphore-osism-kubernetes-push
    max: 1

- job:
    name: osism-kubernetes-build
    pre-run: zuul-playbooks/pre.yml
    run: zuul-playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: abstract-osism-kubernetes-push
    abstract: true
    semaphores:
      - name: semaphore-osism-kubernetes-push
    pre-run: zuul-playbooks/pre.yml
    run: zuul-playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital
      push_image: true

- job:
    name: osism-kubernetes-push
    parent: abstract-osism-kubernetes-push
    secrets:
      - name: secret
        secret: SECRET_OSISM_KUBERNETES
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - hadolint
        - osism-kubernetes-build
        - yamllint
    gate:
      jobs:
        - ansible-lint
        - hadolint
        - osism-kubernetes-build
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - hadolint
        - yamllint
    periodic-midnight:
      jobs:
        - osism-kubernetes-push
    post:
      jobs:
        - osism-kubernetes-push:
            branches: main
    tag:
      jobs:
        - osism-kubernetes-push
