---
- secret:
    name: SECRET_OSISM_KUBERNETES
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - E4KqeSYLZWvnk/RvcXlPK9+9vMpPlcR1T7a8JdoRpEWaHIjSfkR/z6iweljyy1fVFH5wS
          vxzeSPSuFz3w8e47aV6QrxsOekkeghFCXvZv20A5E9Eluzk/vvvLm/5089YK5t7RkHInr
          PUqvcv1yoPjhCO4A8L5+th2aNhjNN4EtVrXL/UGQnCn64v1BUHeLKiCymCO6mI4C1HWV8
          nU0SgqDnwqinVHr6d+ZHhxR2wvDrMcQM7Dti7RZCKesfwgQxnLC0LenP7KI5E4z0W7R+E
          ipHTcrn5p03mgtwUs4wBt8muCUm7xRbIC7vpJvEJf8KpFXVBZxqUWha46OqQ/q+OH4z3p
          vcpSoXaexDXJnMGIYCniN4QarV4zSixvuPmvxV1HowzNzVNuffcFya+2PGCc43WgHmTH6
          SEbuRgX35x2p3g2lTSZgonR2Cj6uyNmvlXg9qVkUwweyJ+/dvyHi8jHoNpi7SG+Xe8MD7
          FBF0rL45l4DTI4+FXoCA10uyT9dDFujuqjxxCzgFoCzEM5CEQZ7xHdsQ0mDgi7QUs/Bzb
          q8BxFwdKRe8lwm72sRUAIkrcBIRMdLPohPAmFqDuh/ASlSBMO+a8JoVpglI6STIAAM6tc
          eJPW0sl33UqeL4mzBe1jTvqD+NsMxHeEtQ/E/ymIyWzwHxK0MjN0fgP3tTfJAc=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - NFbD4TjpIXkwWB7THs9NxmFSD5Rawtlx0DhLlUga1mXc1NzVN++UruucUKyXarWrJEgw7
          i48SSRa6b+795NrC1ZGWH/Pd/oZfCsxMn1YACISRUm/+QEl6+C8r6gB+NLUytl/N+64vo
          zbb9s67wL+F9Qo4BV5QzCZE2Aw9JkfwjxhvaERplGZ6Fxx/ZQNbsUPyjOq863DqI2j11A
          wOdXWZolZli7feCAUdVuhxe+nIctRrA6tmuOarW1R0HWoD59HsocPhqTJaJhsGIOeV7t8
          7/4ZTVLzmm1K0G+hLpmz5WlR4x2wdg3OOOlCjRhlLJhwuxi2iifVXpYBOJuwID4hCJqTS
          x9l5t5+Pbb1GMMF4M3SAJIFE6FoApXQ8STTvwm5hrSU0Jk1vQUIFKTPfJZ7lY6bn7W2Jc
          QBlgBX+P6L7NH86wfTzaXFxTt29/DXgfZb9PBetLElS8RAG7vekLPsdRWTxucN0jGu8PD
          UO7Fz4JaQXY9/wpFjO0Acbhyifv9tWVTP3Atgtk6FFUfMbLdSeQHZHElH8FdoLFKblUeB
          bvLFgQGKhN9Wztn9Rv9WPUdFA53jKSA79AS7bZwXn0sb2tbD05eM8B7Ak4t2QbSOekM0z
          Kfl6tZzw+ah8fnaCIbxm4E0wOmNrL3tpkctbyHGkr5473+HyulaBiHLVxskGT4=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - MHKouuRJANvo9qURBpZ3jNhu5qirGCVdIgk1I19NrQ5Fm7MnJ2s1C/Lr4O+fQ+8vEyV5Z
          GFTg6fWzn5K0HwzrNHI6t/EorpJeXQ8hI+ShDE/V+fABnrcqesbGgy9uc7nIRZsBLB/lj
          0LGOXygeLSYnYYS8gpcQBz3kHWBxwbEwS4eZnrX2/L2mAznbSspiVTxPbGsORTMJI2JI1
          C7tEztbO18igssABR2xmeoTzJ4xEn3Vf8iZPM1gx1Gl7FwLMAs5b4GysEd9vGYHjBLxLB
          8w2ir5I4lGyC2p/njZvRuvLw4QMmcYwCQvNNXggwGcCSwk4NvJ3dRYI69kTS1CDLdVBvH
          tKaUjXVEMjIrjIRYw/WjLCB2Sv+e6qpSeSSL4KcxPVRO8x+q5/hd0Tb/Fuy7wDr2av2tN
          JHdRRR5uts0K2xFsNrClNRWaE65QqewhYl9GmkGkq/M4TA0P5FM6XbtNQRSYg4b3UvsYD
          D3TFTwb3a3TVc75bhk7NKelbuiPy/Gn1Zfef64nwJqexETlPmjTtLsF/563hchqcMhhVF
          gd2Iq2DKaYbBzbpe33RJSwNo2DXt3+fIkmDsdETBNh6FuFHXl3Sa21QktNaPI/N+W/87n
          tM8sWD+u3LLG8lMPMv95EjFmUmc4CL2BrKQsZgGZTMFfup1kzaGg+5JbXw49NY=

- semaphore:
    name: semaphore-osism-kubernetes-push
    max: 1

- job:
    name: osism-kubernetes-build
    pre-run: zuul-playbooks/pre.yml
    run: zuul-playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: abstract-osism-kubernetes-push
    abstract: true
    semaphores:
      - name: semaphore-osism-kubernetes-push
    pre-run: zuul-playbooks/pre.yml
    run: zuul-playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital
      push_image: true
      push_sbom: true

- job:
    name: osism-kubernetes-push
    parent: abstract-osism-kubernetes-push
    secrets:
      - name: secret
        secret: SECRET_OSISM_KUBERNETES
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-collection-ensure-readme
        - ansible-lint
        - flake8
        - hadolint
        - osism-kubernetes-build
        - python-black
        - yamllint
    gate:
      jobs:
        - ansible-collection-ensure-readme
        - ansible-lint
        - flake8
        - hadolint
        - osism-kubernetes-build
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-midnight:
      jobs:
        - osism-kubernetes-push
    post:
      jobs:
        - osism-kubernetes-push:
            branches: main
    tag:
      jobs:
        - osism-kubernetes-push
