---
_memcached_helm_values:
  metrics:
    enable: true
  architecture: high-availability
  replicaCount: 3
  nodeSelector:
    node-role.osism.tech/control-plane: "true"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
