---
container_registry_mariadb_operator: ghcr.io  # noqa var-naming[no-role-prefix]
mariadb_operator_image: "{{ container_registry_mariadb_operator }}/mariadb-operator/mariadb-operator"
# renovate: datasource=docker depName=ghcr.io/mariadb-operator/mariadb-operator
mariadb_operator_image_tag: "v0.0.28"

mariadb_operator_helm_chart_ref: /charts/mariadb-operator
mariadb_operator_helm_release_name: mariadb-operator
mariadb_operator_helm_release_namespace: mariadb-operator
mariadb_operator_helm_values: {}
