apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: neutronl3agents.network.yaook.cloud
spec:
  group: network.yaook.cloud
  names:
    kind: NeutronL3Agent
    plural: neutronl3agents
    shortNames:
    - l3agent
    - l3agents
    singular: neutronl3agent
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current status of the Resource
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: The reason for the current status
      jsonPath: .status.conditions[?(@.type=="Converged")].reason
      name: Reason
      type: string
    - description: The state of the service
      jsonPath: .status.state
      name: State
      type: string
    - description: Eviction status
      jsonPath: .status.eviction.mode
      name: Evicting
      type: string
    - description: Enabled status
      jsonPath: .status.conditions[?(@.type=="Enabled")].status
      name: Enabled
      type: string
    - description: Requires Recreation status
      jsonPath: .status.conditions[?(@.type=="RequiresRecreation")].status
      name: Requires Recreation
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              caCertificates:
                description: CA Certificates that should be added to all services
                  can be placed here. CAs that issue certificates to the service are
                  automatically added and do not need to be specified.
                items:
                  type: string
                type: array
                x-kubernetes-list-type: set
              caConfigMapName:
                type: string
              evictor:
                description: Configuration for the L3 eviction job
                properties:
                  allowFallback:
                    default: true
                    description: This setting allows the evict job to disable the
                      agent if not all routers could be migrated because no agent
                      was available for them. This violates the redundancy and is
                      unsafe
                    type: boolean
                  maxParallelMigrations:
                    default: 15
                    description: Defines how many routers may be evacuated in parallel
                      per iteration
                    type: integer
                  pollInterval:
                    default: 5
                    description: Defines in seconds how long to wait between iterates
                      until the next poll of the API.
                    type: integer
                  respectAvailabilityZones:
                    default: false
                    description: If enabled, excludes all agents where the router
                      is already scheduled except the availibility zone of the agent
                      being evicted.
                    type: boolean
                  verifySeconds:
                    default: 0
                    description: If the value is greater than 0, allows the user to
                      specify how long the API should be queried until the router
                      is active, if this did not work in the defined time period an
                      error is logged
                    type: integer
                type: object
              imagePullSecrets:
                description: References to image pull secrets which should be included
                  in all Pods spawned directly or indirectly by this resource.
                items:
                  description: ''
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              keystoneRef:
                description: Keystone deployment to link this service to
                properties:
                  kind:
                    default: KeystoneDeployment
                    description: Specify the kind of Keystone deployment to reference
                    enum:
                    - KeystoneDeployment
                    - ExternalKeystoneDeployment
                    type: string
                  name:
                    type: string
                required:
                - name
                type: object
              messageQueue:
                properties:
                  amqpServerRef:
                    description: ''
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                required:
                - amqpServerRef
                type: object
              neutronConfig:
                items:
                  additionalProperties:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  description: The keys of this object are the configuration file
                    sections, the values are objects whose keys correspond to config
                    keys within that section.
                  type: object
                type: array
              neutronL3AgentConfig:
                items:
                  additionalProperties:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  description: The keys of this object are the configuration file
                    sections, the values are objects whose keys correspond to config
                    keys within that section.
                  type: object
                type: array
              neutronMetadataAgentConfig:
                items:
                  additionalProperties:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  description: The keys of this object are the configuration file
                    sections, the values are objects whose keys correspond to config
                    keys within that section.
                  type: object
                type: array
              novaRef:
                description: ''
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              region:
                description: Configure the Region to use for this OpenStack service.
                properties:
                  name:
                    default: RegionOne
                    description: Name of the OpenStack region to connect with and
                      to set up the own endpoints in.
                    type: string
                  parent:
                    type: string
                type: object
              resources:
                properties:
                  l3-evict-job:
                    description: Define resource requests/limits for the  container
                    properties:
                      limits:
                        description: Define resource limits for the container
                        properties:
                          cpu:
                            description: CPU time limit for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory limit for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                      requests:
                        description: Define resource requests for the container
                        properties:
                          cpu:
                            description: CPU time request for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory request for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                    type: object
                  neutron-l3-agent:
                    description: Define resource requests/limits for the  container
                    properties:
                      limits:
                        description: Define resource limits for the container
                        properties:
                          cpu:
                            description: CPU time limit for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory limit for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                      requests:
                        description: Define resource requests for the container
                        properties:
                          cpu:
                            description: CPU time request for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory request for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                    type: object
                  neutron-metadata-agent:
                    description: Define resource requests/limits for the  container
                    properties:
                      limits:
                        description: Define resource limits for the container
                        properties:
                          cpu:
                            description: CPU time limit for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory limit for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                      requests:
                        description: Define resource requests for the container
                        properties:
                          cpu:
                            description: CPU time request for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory request for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                    type: object
                type: object
              startupLimitMinutes:
                default: 60
                type: integer
              state:
                default: Enabled
                enum:
                - Enabled
                - Disabled
                - DisabledAndCleared
                type: string
              targetRelease:
                description: The release to deploy. Changing this will trigger an
                  upgrade.
                enum:
                - train
                type: string
            required:
            - keystoneRef
            - caConfigMapName
            - messageQueue
            - neutronL3AgentConfig
            - novaRef
            - targetRelease
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'
                      type: string
                    lastUpdateTime:
                      pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      enum:
                      - Converged
                      - GarbageCollected
                      - Evicted
                      - Enabled
                      - BoundToNode
                      - RequiresRecreation
                      type: string
                  required:
                  - lastTransitionTime
                  - lastUpdateTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              eviction:
                nullable: true
                properties:
                  reason:
                    type: string
                required:
                - reason
                type: object
              installedRelease:
                description: The last successfully deployed release.
                type: string
              nextRelease:
                description: The next release to roll out. This differs from installedRelease
                  during upgrades and from targetRelease during multi-step upgrades.
                type: string
              observedGeneration:
                type: integer
              phase:
                enum:
                - Created
                - Updating
                - WaitingForDependency
                - Updated
                - BackingOff
                - InvalidConfiguration
                type: string
              state:
                default: Creating
                enum:
                - Creating
                - Enabled
                - Disabled
                - Evicting
                - DisabledAndCleared
                type: string
              updatedGeneration:
                type: integer
            required:
            - conditions
            - observedGeneration
            - phase
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
