---
- name: Deploy cert-manager crds
  kubernetes.core.helm:
    release_name: "{{ crds_cert_manager_helm_release_name }}"
    chart_ref: "{{ crds_cert_manager_helm_chart_ref }}"
    release_namespace: "{{ crds_cert_manager_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: /share/kubeconfig
    wait: true
    values: "{{ _crds_cert_manager_helm_values | combine(crds_cert_manager_helm_values, recursive=True) }}"

- name: Deploy prometheus operator crds
  kubernetes.core.helm:
    release_name: "{{ crds_prometheus_operator_helm_release_name }}"
    chart_ref: "{{ crds_prometheus_operator_helm_chart_ref }}"
    release_namespace: "{{ crds_prometheus_operator_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: /share/kubeconfig
    wait: true
    values: "{{ _crds_prometheus_operator_helm_values | combine(crds_prometheus_operator_helm_values, recursive=True) }}"

- name: Deploy yaook operators crds
  kubernetes.core.helm:
    release_name: "{{ crds_yaook_operators_helm_release_name }}"
    chart_ref: "{{ crds_yaook_operators_helm_chart_ref }}"
    release_namespace: "{{ crds_yaook_operators_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: /share/kubeconfig
    wait: true
    values: "{{ _crds_yaook_operators_helm_values | combine(crds_yaook_operators_helm_values, recursive=True) }}"
