---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  loop:
    - "{{ keycloak_operator_directory }}"

- name: Copy keycloak-operator manifest file
  ansible.builtin.template:
    src: "{{ keycloak_operator_template_directory }}/keycloak-operator.yml.j2"
    dest: "{{ keycloak_operator_directory }}/keycloak-operator.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
