---
- name: Deploy ingress-nginx
  kubernetes.core.helm:
    release_name: "{{ ingress_nginx_helm_release_name }}"
    chart_ref: "{{ ingress_nginx_helm_chart_ref }}"
    release_namespace: "{{ ingress_nginx_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: /share/kubeconfig
    wait: true
    values: "{{ _ingress_nginx_helm_values | combine(ingress_nginx_helm_values, recursive=True) }}"
