---
collections:
  - name: ansible.utils
    source: https://galaxy.ansible.com
    version: '5.1.2'
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: '1.6.2'
  - name: community.general
    source: https://galaxy.ansible.com
    version: '9.5.0'
  - name: kubernetes.core
    source: https://galaxy.ansible.com
    version: '5.0.0'
  - name: osism.commons
    source: https://galaxy.ansible.com
    version: '0.20240702.0'
