---
- name: Deploy cloudnative-pg
  kubernetes.core.helm:
    release_name: "{{ cloudnative_pg_release_name }}"
    chart_ref: "{{ cloudnative_pg_chart_ref }}"
    release_namespace: "{{ cloudnative_pg_release_namespace }}"
    create_namespace: true
    wait: true
    values: "{{ _cloudnative_pg_helm_values | combine(cloudnative_pg_helm_values, recursive=True) }}"
