---
- name: Apply cloudnative_pg
  hosts:
    - "{{ hosts_manager|default(groups['manager'][0])|default('localhost') }}"
  connection: local

  tasks:
    - name: Deploy cloudnative-pg helm chart
      kubernetes.core.helm:
        name: cloudnative-pg
        chart_ref: /charts/cloudnative-pg
        release_namespace: cnpg-system
        create_namespace: true
        wait: true
