---
- name: Apply role yaook_operators
  hosts:
    - "{{ hosts_manager|default(groups['manager'][0])|default('localhost') }}"
  connection: local
  gather_facts: false

  tasks:
    - name: Include yaook_operators role
      ansible.builtin.include_role:
        name: yaook_operators
