---
- name: Apply role memcached
  hosts:
    - "{{ hosts_manager|default(groups['manager'][0])|default('localhost') }}"
  connection: local
  gather_facts: false

  tasks:
    - name: Include memcached role
      ansible.builtin.include_role:
        name: memcached
