---
- name: Apply role crds
  hosts:
    - "{{ hosts_manager|default(groups['manager'][0])|default('localhost') }}"
  connection: local
  gather_facts: false

  tasks:
    - name: Include crds role
      ansible.builtin.include_role:
        name: crds
