---
- name: Install Operator Lifecycle Manager (OLM)
  hosts:
    - "{{ hosts_manager|default(groups['manager'][0])|default('localhost') }}"
  connection: local

  tasks:
    - name: Install Operator Lifecycle Manager (OLM)
      ansible.builtin.command: operator-sdk olm install
      register: result
      changed_when: "'Successfully installed OLM version' in result.stdout"
      failed_when: "'Failed to install OLM version' in result.stdout"
