---
- name: Apply role headlamp
  hosts:
    - "{{ hosts_manager|default(groups['manager'][0])|default('localhost') }}"
  connection: local
  gather_facts: false

  tasks:
    - name: Include headlamp role
      ansible.builtin.include_role:
        name: headlamp
