---
- name: Apply headlamp
  hosts:
    - "{{ hosts_manager|default(groups['manager'][0])|default('localhost') }}"
  connection: local

  tasks:
    - name: Deploy headlamp helm chart
      kubernetes.core.helm:
        name: headlamp
        chart_ref: /charts/headlamp
        release_namespace: kube-system
        create_namespace: true
        wait: true
