---
- name: Deploy memcached
  kubernetes.core.helm:
    release_name: "{{ memcached_helm_release_name }}"
    chart_ref: "{{ memcached_helm_chart_ref }}"
    release_namespace: "{{ memcached_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: /share/kubeconfig
    wait: true
    values: "{{ _memcached_helm_values | combine(memcached_helm_values, recursive=True) }}"
