---
- name: Deploy node-feature-discovery
  kubernetes.core.helm:
    release_name: "{{ node_feature_discovery_helm_release_name }}"
    chart_ref: "{{ node_feature_discovery_helm_chart_ref }}"
    release_namespace: "{{ node_feature_discovery_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: /share/kubeconfig
    wait: true
    values: "{{ _node_feature_discovery_helm_values | combine(node_feature_discovery_helm_values, recursive=True) }}"
